--liquibase formatted sql

--  Baseline of the schema that `spring.jpa.hibernate.ddl-auto=update` produced for the entity
--  model as of this changeset. Generated from a real PostgreSQL 16 instance via
--  SchemaBaselineExportTool + `pg_dump --schema-only`, NOT hand-written -- so column names, the
--  @OrderColumn column (response_entry.responses_order), the ordinal `question.type smallint`
--  and Hibernate's generated FK names all match production exactly.
--
--  This changeset is self-aware: the precondition below checks whether `test_session` already
--  exists. On the existing production database it is MARKed as RAN without executing a single
--  statement; on a fresh database (a test container, a new dev DB) it actually creates the schema.
--  That means the first Liquibase deploy needs NO manual `changelog-sync` step -- which was the
--  riskiest manual operation in the rollout.

--changeset studease:001-baseline
--preconditions onFail:MARK_RAN onError:HALT
--precondition-sql-check expectedResult:0 SELECT COUNT(*) FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'test_session'
--comment Initial schema baseline, captured from the live ddl-auto=update schema.

CREATE TABLE public.answer (
    is_correct boolean,
    id bigint NOT NULL,
    question_id bigint NOT NULL,
    dtype character varying(31) NOT NULL,
    content character varying(255),
    left_option character varying(255),
    right_option character varying(255)
);

ALTER TABLE public.answer ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.answer_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.authorities (
    reference uuid NOT NULL,
    authority character varying(255) NOT NULL,
    CONSTRAINT authorities_authority_check CHECK (((authority)::text = ANY ((ARRAY['ROLE_USER'::character varying, 'ROLE_ADMIN'::character varying])::text[])))
);

CREATE TABLE public.collection (
    id bigint NOT NULL,
    author_user_reference uuid,
    name character varying(255)
);

ALTER TABLE public.collection ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.collection_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.question (
    points integer,
    type smallint,
    collection_id bigint,
    id bigint NOT NULL,
    test_id uuid,
    content character varying(255),
    CONSTRAINT question_type_check CHECK (((type >= 0) AND (type <= 3)))
);

ALTER TABLE public.question ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.question_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.response_entry (
    responses_order integer,
    id bigint NOT NULL,
    question_id bigint,
    test_session_id bigint
);

CREATE TABLE public.response_entry_answers (
    answers_id bigint NOT NULL,
    response_entry_id bigint NOT NULL
);

ALTER TABLE public.response_entry ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.response_entry_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.sample (
    points integer,
    questions_count integer,
    collection_id bigint,
    id bigint NOT NULL,
    test_id uuid
);

ALTER TABLE public.sample ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sample_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.test (
    maximum_score integer,
    minutes_to_complete integer,
    deadline timestamp(6) without time zone,
    open_date timestamp(6) without time zone,
    author_user_reference uuid,
    id uuid NOT NULL,
    name character varying(255)
);

CREATE TABLE public.test_session (
    current_question_index integer,
    mark integer,
    ends_at timestamp(6) without time zone,
    finished_at timestamp(6) without time zone,
    id bigint NOT NULL,
    started_at timestamp(6) without time zone,
    test_id uuid,
    student_group character varying(255),
    student_name character varying(255)
);

ALTER TABLE public.test_session ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.test_session_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.users (
    balance integer,
    is_active boolean,
    user_reference uuid NOT NULL,
    email character varying(255),
    first_name character varying(255),
    last_name character varying(255),
    password character varying(255)
);

CREATE TABLE public.users_authorities (
    authorities_reference uuid NOT NULL,
    users_user_reference uuid NOT NULL
);

ALTER TABLE ONLY public.answer
    ADD CONSTRAINT answer_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.authorities
    ADD CONSTRAINT authorities_authority_key UNIQUE (authority);

ALTER TABLE ONLY public.authorities
    ADD CONSTRAINT authorities_pkey PRIMARY KEY (reference);

ALTER TABLE ONLY public.collection
    ADD CONSTRAINT collection_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.question
    ADD CONSTRAINT question_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.response_entry
    ADD CONSTRAINT response_entry_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.sample
    ADD CONSTRAINT sample_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.test
    ADD CONSTRAINT test_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.test_session
    ADD CONSTRAINT test_session_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.users_authorities
    ADD CONSTRAINT users_authorities_pkey PRIMARY KEY (authorities_reference, users_user_reference);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (user_reference);

ALTER TABLE ONLY public.sample
    ADD CONSTRAINT fk28nw2g9dkr1vur095iue5205f FOREIGN KEY (collection_id) REFERENCES public.collection(id);

ALTER TABLE ONLY public.test_session
    ADD CONSTRAINT fk42kp884nu38qvylfkxa76evuj FOREIGN KEY (test_id) REFERENCES public.test(id);

ALTER TABLE ONLY public.answer
    ADD CONSTRAINT fk8frr4bcabmmeyyu60qt7iiblo FOREIGN KEY (question_id) REFERENCES public.question(id);

ALTER TABLE ONLY public.question
    ADD CONSTRAINT fk8hejcpbbiq1qje11346akp3uj FOREIGN KEY (test_id) REFERENCES public.test(id);

ALTER TABLE ONLY public.users_authorities
    ADD CONSTRAINT fk8hytrlungg1xds7vhbe4ykj14 FOREIGN KEY (users_user_reference) REFERENCES public.users(user_reference);

ALTER TABLE ONLY public.collection
    ADD CONSTRAINT fk9lbgiybyk3u3fwkytlv3okovj FOREIGN KEY (author_user_reference) REFERENCES public.users(user_reference);

ALTER TABLE ONLY public.users_authorities
    ADD CONSTRAINT fkga7nn41tjnhof62tpg9vn58t3 FOREIGN KEY (authorities_reference) REFERENCES public.authorities(reference);

ALTER TABLE ONLY public.response_entry
    ADD CONSTRAINT fknubxbwqbq06e6fg40enrihmt6 FOREIGN KEY (test_session_id) REFERENCES public.test_session(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.response_entry_answers
    ADD CONSTRAINT fkogsw1fqffsl6r75hhauju7g8v FOREIGN KEY (response_entry_id) REFERENCES public.response_entry(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.response_entry
    ADD CONSTRAINT fkokp97yrn3dv3raewacitu2knm FOREIGN KEY (question_id) REFERENCES public.question(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.sample
    ADD CONSTRAINT fkph6lnml9ul8x4m4pmkopua396 FOREIGN KEY (test_id) REFERENCES public.test(id);

ALTER TABLE ONLY public.response_entry_answers
    ADD CONSTRAINT fkpxpxm5ry0a42odf05wumvusl FOREIGN KEY (answers_id) REFERENCES public.answer(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.test
    ADD CONSTRAINT fkqnxew93pc600kv7me8vo6adex FOREIGN KEY (author_user_reference) REFERENCES public.users(user_reference);

ALTER TABLE ONLY public.question
    ADD CONSTRAINT fkrnwx50xjk55srv6cyxglk81vi FOREIGN KEY (collection_id) REFERENCES public.collection(id);

--rollback DROP TABLE IF EXISTS public.answer CASCADE;
--rollback DROP TABLE IF EXISTS public.authorities CASCADE;
--rollback DROP TABLE IF EXISTS public.collection CASCADE;
--rollback DROP TABLE IF EXISTS public.question CASCADE;
--rollback DROP TABLE IF EXISTS public.response_entry CASCADE;
--rollback DROP TABLE IF EXISTS public.response_entry_answers CASCADE;
--rollback DROP TABLE IF EXISTS public.sample CASCADE;
--rollback DROP TABLE IF EXISTS public.test CASCADE;
--rollback DROP TABLE IF EXISTS public.test_session CASCADE;
--rollback DROP TABLE IF EXISTS public.users CASCADE;
--rollback DROP TABLE IF EXISTS public.users_authorities CASCADE;
